### ISSUE TITLE
能写个教程 怎么编译 这个kernel么， 小白。

### ISSUE THREAD

**Issue by zhaojinzhou** [KJ-Network/K-Nel-M1721#1]

**Comment by KNKJ55** [comment]
这个吧，不太好说
大致就是准备编译环境，准备工具链，拉源码和编译
编译环境最好用ubuntu，手机装一个Linux容器，有root用chroot没root就用proot，电脑的话可以用wsl或虚拟机，如果你想直接装在实体机上也可以，不过我个人不是很喜欢Ubuntu，我实体机装的是archlinux
工具链手机找arm的clang9和gcc就行，电脑找x86的clang9和gcc
具体可以参照kernelsu仓库的讨论中的一个名为“[基础教程]如何编译一个ARM64内核”那篇show and talk，剩下的就慢慢研究吧，这玩意一时半会搞不懂的

**Comment by KNKJ55** [comment]
参见https://github.com/tiann/KernelSU/discussions/950

**Comment by KNKJ55** [comment]
搞了github actions，可以fork仓库云编译玩了
