### ISSUE TITLE
刷了内核之后   安装docker，报这个错误

### ISSUE THREAD

**Issue by zhaojinzhou** [KJ-Network/K-Nel-M1721#10]
INFO[2024-09-25T07:27:07.502554187Z] containerd not running, starting managed containerd
INFO[2024-09-25T07:27:07.509354344Z] started new containerd process                address=/data/docker/run/docker/containerd/containerd.sock module=libcontainerd pid=3838
**_ERRO[0000] failure getting variant                       error="getCPUInfo for OS android: not implemented"_**
INFO[2024-09-25T07:27:07.787320802Z] starting containerd                           revision=3dce8eb055cbb6872793272b4f20ed16117344f8.m version=v1.6.21.m

**Comment by zhaojinzhou** [comment]
sudo dockerd --iptables=false
INFO[2024-09-25T07:27:07.448609500Z] Starting up
WARN[2024-09-25T07:27:07.499393562Z] could not change group /data/docker/run/docker.sock to docker: group docker not found
INFO[2024-09-25T07:27:07.502554187Z] containerd not running, starting managed containerd
INFO[2024-09-25T07:27:07.509354344Z] started new containerd process                address=/data/docker/run/docker/containerd/containerd.sock module=libcontainerd pid=3838
ERRO[0000] failure getting variant                       error="getCPUInfo for OS android: not implemented"
INFO[2024-09-25T07:27:07.787320802Z] starting containerd                           revision=3dce8eb055cbb6872793272b4f20ed16117344f8.m version=v1.6.21.m
INFO[2024-09-25T07:27:07.846118250Z] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2024-09-25T07:27:07.858113666Z] skip loading plugin "io.containerd.snapshotter.v1.aufs"...  error="aufs is not supported (modprobe aufs failed: exit status 1 \"No module configuration directories given.\\nUsage:\\n\\n  modprobe [-alrqvsDb] [-d DIR] [MODULE]+\\n  modprobe [-alrqvsDb] [-d DIR] MODULE [symbol=value][...]\\n\\nOptions:\\n  -b: Apply blocklist to module names too\\n  -d: Load modules from DIR, option may be used multiple times\\n  -D: Print dependencies for modules only, do not load  -h: Print this help\\n  -l: List modules matching pattern\\n  -r: Remove MODULE (multiple modules may be specified)\\n  -q: Quiet\\n  -v: Verbose\\n\\n\"): skip plugin" type=io.containerd.snapshotter.v1
INFO[2024-09-25T07:27:07.858327625Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2024-09-25T07:27:07.858450646Z] loading plugin "io.containerd.snapshotter.v1.devmapper"...  type=io.containerd.snapshotter.v1
WARN[2024-09-25T07:27:07.858518041Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
INFO[2024-09-25T07:27:07.858562312Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2024-09-25T07:27:07.860023250Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2024-09-25T07:27:07.861118041Z] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2024-09-25T07:27:07.895698927Z] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  error="path /data/docker/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2024-09-25T07:27:07.895861166Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2024-09-25T07:27:07.896001375Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
INFO[2024-09-25T07:27:07.896047729Z] metadata content store policy set             policy=shared
INFO[2024-09-25T07:27:07.898390645Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2024-09-25T07:27:07.898664031Z] loading plugin "io.containerd.event.v1.exchange"...  type=io.containerd.event.v1
INFO[2024-09-25T07:27:07.898735698Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2024-09-25T07:27:07.899135333Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2024-09-25T07:27:07.900679916Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2024-09-25T07:27:07.900976791Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2024-09-25T07:27:07.901530645Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2024-09-25T07:27:07.903786531Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.903923093Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.903996270Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.904072260Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.904130854Z] loading plugin "io.containerd.service.v1.introspection-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.904205333Z] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.904268614Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.904324343Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.904391062Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2024-09-25T07:27:07.904486687Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.904555281Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.904612833Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.904685489Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.904735906Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.904800281Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.904854083Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.904904552Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.904951791Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.905017208Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.905101427Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.905195073Z] loading plugin "io.containerd.tracing.processor.v1.otlp"...  type=io.containerd.tracing.processor.v1
INFO[2024-09-25T07:27:07.905271583Z] skip loading plugin "io.containerd.tracing.processor.v1.otlp"...  error="no OpenTelemetry endpoint: skip plugin" type=io.containerd.tracing.processor.v1
INFO[2024-09-25T07:27:07.905321791Z] loading plugin "io.containerd.internal.v1.tracing"...  type=io.containerd.internal.v1
ERRO[2024-09-25T07:27:07.905548406Z] failed to initialize a tracing processor "otlp"  error="no OpenTelemetry endpoint: skip plugin"
INFO[2024-09-25T07:27:07.905705698Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2024-09-25T07:27:07.905936062Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2024-09-25T07:27:07.908582625Z] serving...                                    address=/data/docker/run/docker/containerd/containerd-debug.sock
INFO[2024-09-25T07:27:07.908972364Z] serving...                                    address=/data/docker/run/docker/containerd/containerd.sock.ttrpc
INFO[2024-09-25T07:27:07.909272729Z] serving...                                    address=/data/docker/run/docker/containerd/containerd.sock
INFO[2024-09-25T07:27:07.909390229Z] containerd successfully booted in 0.163546s
INFO[2024-09-25T07:27:08.010641739Z] [graphdriver] trying configured driver: overlay2
INFO[2024-09-25T07:27:08.024571114Z] Loading containers: start.
INFO[2024-09-25T07:27:08.073595593Z] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[2024-09-25T07:27:08.080671270Z] Loading containers: done.
WARN[2024-09-25T07:27:08.081644968Z] Could not get operating system name: open /usr/lib/os-release: no such file or directory
WARN[2024-09-25T07:27:08.081859239Z] Could not get operating system version: open /usr/lib/os-release: no such file or directory
WARN[2024-09-25T07:27:08.161815020Z] failed to retrieve /data/data/com.termux/files/usr/bin/docker-init version: exit status 1
INFO[2024-09-25T07:27:08.174600125Z] Docker daemon                                 commit=ed223bc graphdriver=overlay2 version=dev
INFO[2024-09-25T07:27:08.175807104Z] Daemon has completed initialization
INFO[2024-09-25T07:27:08.234371010Z] API listen on /data/docker/run/docker.sock

**Comment by KNKJ55** [comment]
很多时候可能不是内核的问题，毕竟K-Nel只提供支持，剩下的都要靠你自己

参见https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27?permalink_comment_id=4064066 中 Colo-Thor的回复: 
`~ $ sudo docker run hello-world
ERRO[0000] failure getting variant error="getCPUInfo for OS android: not implemented"

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:

The Docker client contacted the Docker daemon.
The Docker daemon pulled the "hello-world" image from the Docker Hub.
(arm64v8)
The Docker daemon created a new container from that image which runs the
executable that produces the output you are currently reading.
The Docker daemon streamed that output to the Docker client, which sent it
to your terminal.
To try something more ambitious, you can run an Ubuntu container with:
$ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
https://hub.docker.com/

For more examples and ideas, visit:
https://docs.docker.com/get-started/

~ $`

reslove by pkg install root-repo && pkg install docker
