### ISSUE TITLE
那个...能更新KernelSU至1.0.0吗喵？

### ISSUE THREAD

**Issue by meowteaneo** [KJ-Network/K-Nel-M1721#2]

**Comment by KNKJ55** [comment]
抱歉搁的太久了
更新到1.0.0肯定是不能了，KernelSU在1.0.0时放弃了非GKI设备，非GKI设备可用的KernelSU最新版是0.9.5，不过，我们的内测版已经更新到0.9.5了，如果您有需要，我们可以开放出来

**Comment by KNKJ55** [comment]
https://github.com/KJ-Network/K-Nel-M1721/releases/tag/M1721-C-1.62
这个pre-release版本把kernelsu更新到了0.9.5
关于kernelsu不再支持非gki设备的信息，请参阅https://github.com/tiann/KernelSU/issues/1705

**Comment by KNKJ55** [comment]
已更新
使用第三方fork，非官方
